### PR TITLE
attempted cleanup for HTML escaping

### PR DESCRIPTION
**Pull request by fsiler**

### CODE REVIEW

**Comment by stevebauman** [comment]
These tags are intentional to allow for HTML to be unescaped. For example if someone adds a link to a column, then it would display the raw HTML.

**Comment by fsiler** [comment]
Right, but if someone is storing text in their database, let's say, then HTML gets through unescaped.  Would you be willing to accept a patch that lets the user set a flag if their columns contain HTML, and otherwise assumes it should be escaped?

**Comment by stevebauman** [comment]
Hi, sorry for the long response here, you're right. I originally accepted a pull to allow it to be unescaped by default, but it should be escaped by default. I'll accept a PR if you're interested in making one, however I'll be fixing this tomorrow as well.

**Comment by fsiler** [comment]
I'm not an expert on Laravel or github- how does the test suite work, and does it run unit tests, or is it just checking for compilation or something?  It would probably help make this more robust if there was an easy way to add tests for all the different cases and run them against Laravel 4 and 5- I only patched 5, which might cause confusion for folks using 4.

I actually just stumbled across this library for use in a code demo- I didn't get the job, but I'm happy to help patch, especially if there's a way to build sustainable unit and regression testing in as we go.

**Pull request closed without merging**
