### PR TITLE
Link Column

### PR DESCRIPTION
**Pull request by mix359**
I've created this new function that permit to add some columns with a link/button inside.
It can be useful to create for example edit or delete link in an administration table.
I've added the function, that add a new column (for the label) and a column modification (with the html) and a view for the button link (so it's fully customizable)

### CODE REVIEW

**Comment by stevebauman** [comment]
I like the idea, however you can already return your own view / string for a specific column per row using `modify()`. For example:

    $books->columns([
        'actions' => 'Actions',
    ])->modify('actions', function($book)
    {
        return view('books.actions', compact('book');
    })
    ->render();

You could event extend this by adding an `actions` accessor to your `Book` model:

    class Book extends Eloquent {
        public function getActionsAttribute()
        {
            return view('books.actions', ['book' => $this]);
        }
    }

**Comment by mix359** [comment]
Hi,
Thanks for the answer.
Yes, it's true that I can realize it with the modify, but it's not versatile in the condition that i need:
At the moment I only need to do this, to have 2 link... 1 line of code instead of ~5 (the column in the array, and the 3-4 row of closure)
```
$activities->columns(['name' => "Name"])
			->addLinkColumn("edit","Modify",url("controller/edit-activity-type/%id"))
			->addLinkColumn("delete","Delete",url("controller/delete-activity-type/%id"))
			->render();
```

I have to specify only the useful information, like the the link name and url structure. Instead, using a closure function, I've to rewrite the same code many times (that is logically identical all the times), with only 2 variables that change.

I cannot use the accessor in the model, because many different controller can use the same "edit link" but with different path (and only the controller know the right path... is not right to write a path of controller action inside a model)

I've also think to create a standard closure function to pass to the modify function, that do the link job, like in that way:
```
$books->columns([
    'actions' => 'Actions',
])->modify('actions', $actionClosure)
->render();
```

But I cannot pass other variable (like the link name and path) to a closure in a variable.

The only other method I've left, is create an helper function, in the helper file, that have the same argoment, and return a closure to pass to the modify variable.
Should I try to do something like that, and send it?

Thanks again
Mix

**Comment by stevebauman** [comment]
You're right about how there could be different paths so having an accessor on the model might not be a good choice, however the solution you're incorporating is limited to one `id` column. What if I had multiple nested routes with many ID's or slugs (for an example, `users/{user_id}/posts/{post_id}/comments`)? You're creating a new type of routing that developers would need to learn specifically for eloquent table.

Also, you include a closure mechanism in case more code is needed to generate a link, but then this is already covered by the `modify()` column.

You're free to extend the eloquent table `TableTrait` with your own implementation and include this method, then you'd have more flexibility anyway and can add functionality as you please.

**Comment by mix359** [comment]
Thanks for the answer
> Also, you include a closure mechanism in case more code is needed to generate a link, but then this is already covered by the modify() column.

There's a little difference: that closure have access to the link label and link path variable, that the closure in modify doesn't have (I pass to the clousure $record, $label, $link, $key, instead of only the $record)
So If someone would create a more complex links, using those data, they can create a closure, put in a variable, and reuse this closure for all his links. (I cannot pass external argument, to a closure passed to modify)
(if you need, I can provide you some example)

About the nasted id, it's true, so, I'm adding a way to access to the other attribute of the model. But probably, the other data to construct the url is already know in the controller (or can be passed to the view, from the controller) when you are calling the addLinkColumn function, so you can add they directly in the url you're passing to the function. For example:
```
$messages->columns(['message' => "Comment Message"])
            ->addLinkColumn("edit","Modify",url("users/{$userId}/posts/{$postId}/comments/%key/edit"))
            ->addLinkColumn("delete","Delete",url("users/{$userId}/posts/{$postId}/comments/%key/edit"))
            ->render();
```

Now I will work to add the support of the other model parameter.

About the extension of the TableTrait, I've currently added the function in it :)
I hope it's good in this way ;)

Thanks again
Mix

**Comment by mix359** [comment]
Sorry, how could I resend the pull request? I've to open a new one?
I've commited the new code in my repository

**Pull request closed without merging**
